version: "3.7"
services:

  Reclamation:
    container_name: reclamation
    build:
      context: .
      dockerfile: ./Reclamation/Dockerfile
    ports:
      - "8082:8082"
    hostname: localhost
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://serviceregistry:8761/eureka/
    image: "service-reclamtion"
    depends_on:
      - Eureka


  Review:
    container_name: review
    build:
      context: .
      dockerfile: ./Reviews/Dockerfile
    ports:
      - "8084:8084"
    hostname: localhost
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://serviceregistry:8761/eureka/
    image: "service-review"
    depends_on:
      - Eureka


    
  Category:
    container_name: Category
    build:
      context: .
      dockerfile: ./Category/Dockerfile
    ports:
      - "8085:8085"
    hostname: localhost
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://serviceregistry:8761/eureka/
    image: "category"
    depends_on:
      - Eureka



  Service:
    container_name: service
    build:
      context: .
      dockerfile: ./Service/DockerFile
    ports:
      - "8083:8083"
    hostname: localhost
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://serviceregistry:8761/eureka/
    image: "service"
    depends_on:
      - Eureka





  Commande:
    container_name: commande
    build:
      context: .
      dockerfile: ./Commande_micro/Dockerfile
    ports:
      - "8088:8088"
    hostname: localhost
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://serviceregistry:8761/eureka/
    image: "commande"
    depends_on:
      - Eureka


  Subscription:
    container_name: subscription
    build:
      context: .
      dockerfile: ./MicroSubscription/Dockerfile
    ports:
      - "8086:8086"
    hostname: localhost
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://serviceregistry:8761/eureka/
    image: "subscription"
    depends_on:
      - Eureka

  gateway:
    build:
      context: ./API_Gateway_Server
    ports:
      - "8081:8081"
    image: "apigateway"
    depends_on:
      - Eureka
    environment:
      - eureka.client.serviceUrl.defaultZone=http://serviceregistry:8761/eureka/
    networks:
      - mynetwork


  Eureka:
    container_name: serviceregistry
    build:
      context: ./EurekaServer
    ports:
      - "8761:8761"
    hostname: serviceregistry
    image: "eureka"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://serviceregistry:8761/eureka/

  mysql:
    image: mysql
    #restart: unless-stopped
    networks:
      - internal
    ports:
      - "3306:3306"
    volumes:
      - ./local_data_save:/var/lib/mysql
      - ./dbScripts:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin

networks:
  mynetwork:
    driver: bridge
  external:
    driver: bridge
  internal:
    driver: bridge

