FROM openjdk:17
EXPOSE 8089
ADD target/projet_microservice-0.0.1-SNAPSHOT.jar projet_microservice-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","projet_microservice-0.0.1-SNAPSHOT.jar"]
ADD src/main/resources/application.properties application.properties