version: '3'
services:
  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Subscription
      MYSQL_USER: projet
      MYSQL_PASSWORD: projet
    healthcheck:
      test: ["CMD-SHELL", 'mysqladmin -uroot -proot ping']
      interval: 10s
      timeout: 2s
    ports:
      - "6033:3306"
#    volumes:
#      - data:/var/lib/mysql

  # Wait for MySQL to be joinable.
  check-db-started:
    image: jwilder/dockerize:0.6.1
    container_name: check-db-started
    links:
      - db
    depends_on:
      - db
    command: 'dockerize -wait=tcp://db:3306'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80

  subscription:
    container_name: subscription
    links:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8089:8089"
    depends_on:
      - check-db-started
#volumes:
#  data:

