version: "2.2"
services:

  Reclamation:
    container_name: reclamation
    build:
      context: ./
      dockerfile: Docker-reclamation
    ports:
      - "8082:8082"
    hostname: localhost
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://serviceregistry:8761/eureka/
    image: "chat"
    depends_on:
      - Eureka


  Eureka:
    container_name: serviceregistry
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    hostname: serviceregistry
    image: "eureka"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://serviceregistry:8761/eureka/