version: "2.2"
services:

  Reclamation:
    container_name: reclamation
    build:
      context: ./
      dockerfile: Docker-reclamation
    ports:
      - "8082:8082"
    hostname: localhost
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://serviceregistry:8761/eureka/
    image: "reclamation"
    depends_on:
      - Eureka


  Review:
    container_name: review
    build:
      context: ./
      dockerfile: Docker-review
    ports:
      - "8084:8084"
    hostname: localhost
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://serviceregistry:8761/eureka/
    image: "review"
    depends_on:
      - Eureka



  Service:
    container_name: service
    build:
      context: ./
      dockerfile: Docker-service
    ports:
      - "8083:8083"
    hostname: localhost
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://serviceregistry:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://docker-mysql_2:3306/base_service?autoReconnect=true&useSSL=false
    image: "service"
    depends_on:
      - Eureka
      - docker-mysql_2

  docker-mysql_2:
    image: "mysql:5.6"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_DATABASE=base_service
    ports:
      - 3308:3306
  Commande:
    container_name: commande
    build:
      context: ./
      dockerfile: dockerfile-commande
    ports:
      - "8080:8080"
    hostname: localhost
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://serviceregistry:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://docker-mysql_1:3306/commande_micro?autoReconnect=true&useSSL=false
    image: "commande"
    depends_on:
      - Eureka
      - docker-mysql_1
  docker-mysql_1:
    image: "mysql:5.6"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_DATABASE=commande_micro
    ports:
      - 3309:3306
  Subscription:
    container_name: subscription
    build:
      context: ./
      dockerfile: dockerfile-subscription
    ports:
      - "8089:8089"
    hostname: localhost
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://serviceregistry:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://docker-mysql_3:3306/Subscription?autoReconnect=true&useSSL=false
    image: "subscription"
    depends_on:
      - Eureka
      - docker-mysql_3
  docker-mysql_3:
    image: "mysql:5.6"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=Subscription
    ports:
      - 3307:3306
  Eureka:
    container_name: serviceregistry
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    hostname: serviceregistry
    image: "eureka"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://serviceregistry:8761/eureka/